bug-hunt-front:
  component: '@sls-next/serverless-component@3.5.3'
  inputs:
    deploy: true
    bucketName: 's3버킷이름'
    bucketRegion: 'ap-northeast-2' // 버킷 지역
    nextConfigDir: './'
    name:
      defaultLambda: dafuaultLambda
      imageLambda: imageLambda

    cloudfront:
      comment: 'next deploy' # CloudFront 설명 설정